#!/bin/bash

# secretlint:
# https://github.com/secretlint/secretlint?tab=readme-ov-file#bash-script

if ! command -v secretlint &>/dev/null; then
	echo "secretlint is not installed"
	exit 1
fi

files=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$files" ] && exit 0

secretlintrc="$HOME/.config/secretlint/.secretlintrc.json"
if [ -f .secretlintrc.json ]; then
	secretlintrc=".secretlintrc.json"
fi

# Secretlint all selected files
echo "$files" | xargs secretlint --secretlintrc "$secretlintrc"
ret=$?

if [ $ret -ne 0 ] ;then
	exit $ret
fi

num_files=$(echo "$files" | wc -l)
suffix=""
[ "$num_files" -gt 1 ] && suffix="s"

echo "[secretlint]"
echo " $num_files file$suffix checked:"
for file in $files; do
	echo " $file"
done
echo ""
