#!/bin/bash

# secretlint:
# https://github.com/secretlint/secretlint?tab=readme-ov-file#bash-script

if ! command -v secretlint &>/dev/null; then
	echo "secretlint is not installed"
	exit 1
fi

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

SECRETLINTRC="$HOME/.config/secretlint/.secretlintrc.json"
if [ -f .secretlintrc.json ]; then
	SECRETLINTRC=".secretlintrc.json"
fi

# Secretlint all selected files
echo "$FILES" | xargs secretlint --secretlintrc "$SECRETLINTRC"
RET=$?

if [ $RET -ne 0 ] ;then
	exit $RET
fi

NUM_FILES=$(echo "$FILES" | wc -l)
SUFFIX=""
[ "$NUM_FILES" -gt 1 ] && SUFFIX="s"

echo "[secretlint]"
echo " $NUM_FILES file$SUFFIX checked:"
for file in $FILES; do
	echo " $file"
done
echo ""
